name: Terraform Dev Auto Apply

on:
  push:
    branches: 
     - master
    
env:
  TF_VERSION: 1.7.5
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev
    
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          if [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            terraform plan -destroy -out=tfplan
          else
            terraform plan -out=tfplan
          fi

      - name: Terraform Apply
        if: github.event.inputs.action != 'destroy' || github.event_name == 'push'
        run: terraform apply tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
